name: marinarodil
favicon: null
layout_spectrum: 0.305616443278268
typography_spectrum: 0.03524230350740254
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.32685801316984
  lightness: 0.9937008996494114
  saturation: 0.4670226606540382
  rhythmicContrast: 0.4726665047928691
purpose: []
