name: marinarodil
favicon: null
layout_spectrum: 0.305616443278268
typography_spectrum: 0.00495
title: Diseño gráfico editorial e interactivo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.375
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
